export enum AnimeGenre {
    Action = "Action",
    Adventure = "Adventure",
    Comedy = "Comedy",
    Drama = "Drama",
    Fantasy = "Fantasy",
    Horror = "Horror",
    Isekai = "Isekai",
    Mystery = "Mystery",
    Romance = "Romance",
    SciFi = "Sci-Fi",
    Shounen = "Shounen",
    Shoujo = "Shoujo",
    Seinen = "Seinen",
    SliceOfLife = "Slice of Life",
    Sports = "Sports",
    Supernatural = "Supernatural",
    Thriller = "Thriller",
    Yaoi = "Yaoi",
    Yuri = "Yuri",
  };